apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret-file
type: Opaque
data: # name of the secret file which we will later use to mount volume secret.file
  secret.file: |
    c29tZXN1cGVyc2VjcmV0IGZpbGUgY29udGVudHMgbm9ib2R5IHNob3VsZCBzZWU=